#test
executor: 'CeleryExecutor'

auth:
  forcePassword: false
  username: user
  password: ydomZ1TYF4
  fernetKey: dFNXQUpidDRWT2cwamtyZElmT1RTMGpBejBMNmJhOUs=

web:
  image:
    registry: docker.io
    repository: bitnami/airflow
    tag: 1.10.14-debian-10-r28
    pullPolicy: IfNotPresent
#   replicaCount: 1

#   containerPort: 8088 #8080
  
#   livenessProbe:
#     enabled: true
#     initialDelaySeconds: 240
#     periodSeconds: 20
#     timeoutSeconds: 5
#     failureThreshold: 6
#     successThreshold: 1
#   readinessProbe:
#     enabled: true
#     initialDelaySeconds: 60
#     periodSeconds: 10
#     timeoutSeconds: 5
#     failureThreshold: 6
#     successThreshold: 1

scheduler:
  image:
    registry: docker.io
    repository: bitnami/airflow-scheduler
    tag: 1.10.14-debian-10-r38
    pullPolicy: IfNotPresent      
#   replicaCount: 1

worker: 
  image:
    registry: docker.io
    repository: bitnami/airflow-worker
    tag: 1.10.14-debian-10-r38
    pullPolicy: IfNotPresent
#   port: 8543 #8793 
#   replicaCount: 1

#   livenessProbe:
#     enabled: true
#     initialDelaySeconds: 240
#     periodSeconds: 20
#     timeoutSeconds: 5
#     failureThreshold: 6
#     successThreshold: 1
#   readinessProbe:
#     enabled: true
#     initialDelaySeconds: 60
#     periodSeconds: 10
#     timeoutSeconds: 5
#     failureThreshold: 6
#     successThreshold: 1

git:
  image:
    registry: docker.io
    repository: bitnami/git
    tag: 2.30.0-debian-10-r11
    pullPolicy: IfNotPresent
  dags:
    enabled: true
    repositories:
      - repository: https://github.com/Aymaru/dags-test.git
        branch: main
        name: dags-test
        path: ./dags
  sync:
    interval: 60

# service:
#   type: ClusterIP
#   port: 8088 #8080

postgresql:
  enabled: true
  postgresqlUsername: bn_airflow
  postgresqlPassword: JSOi0H4v8n
  # postgresqlDatabase: bitnami_airflow
# externalDatabase:
#   host: localhost
#   user: bn_airflow 
#   password: admin
#   database: bitnami_airflow
#   port: 5555 #5432

redis:
#   enabled: true
#   cluster:
#     enabled: false  
  password: 1JemwRGPob

# externalRedis: 
#   host: localhost
#   port: 6666 #6379 
#   password: admin
#   username: admin

# metrics:
#   enabled: false

#   image:
#     registry: docker.io
#     repository: bitnami/airflow-exporter
#     tag: 0.20180711.0-debian-10-r326
#     pullPolicy: IfNotPresent

#   podAnnotations:
#     prometheus.io/scrape: 'true'
#     prometheus.io/port: '9112'
 
ingress:
  enabled: true
  #pathType: ImplementationSpecific
  certManager: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-snprod"
  hosts:
    - name: airflow.smartnow.la
      path: /
      tls: true
      tlsHosts: [
        airflow.smartnow.la
      ]
      tlsSecret: airflow.local-tls